# Generated by Django 5.0.7 on 2024-07-31 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backent', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='books',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='books',
            name='author',
            field=models.CharField(default='l', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='books',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='books',
            name='image',
            field=models.ImageField(upload_to='books/'),
        ),
        migrations.AlterField(
            model_name='books',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
